feat: add workflow to test before pull request
MediBird/caring-note-api-server pull request #8
Opened 2024-11-28 13:57 UTC by jawsbaek

2024-11-28 22:34 UTC, ChoiSunPil requested changes
local DB에 의존적인 테스크 코드들이 
있어서 test 수행시 오류 발생할 것으로 보입니다.

Gitaction에서
test step 생략

또는 
test용 properties 분리하여 
개발 db 호출 테스트

하도록 해야 할 것 같아요!

2024-11-28 23:45 UTC, jawsbaek commented
테스트 코드를 디비 의존적이지 않도록 모킹하는 방법을 고려해보시져

2024-11-28 23:45 UTC, jawsbaek commented
제가 테스트 코드 모킹을 한 번 진행해볼게요

2024-11-29 01:02 UTC, ChoiSunPil commented
Repository Mocking도 
좋은 생각인거 같습니다!

다만 해당 방식 적용 시
repository 테스트는 생략해야겠군요

2024-11-29 03:53 UTC, jawsbaek commented
> Repository Mocking도 
> 좋은 생각인거 같습니다!
> 
> 다만 해당 방식 적용 시
> repository 테스트는 생략해야겠군요

맞습니당.
Repository test는
@Disabled를 걸면 전체 테스트에서 제외되어서 
각각 테스트 하는 방식으로 가면 될 것 같아요.

2024-11-29 12:10 UTC, closed without merging